### ISSUE TITLE
Encryption required for demo login

### ISSUE THREAD

**Issue by Tenelia** [dan-lind/igzplugin#1]
"API call failed with status code 400 and body {"errorCode":"error.public-api.failure.encryption.required"}
org.springframework.web.client.HttpClientErrorException: 400 Bad Request"

Let me know if you want the full log!

**Comment by dan-lind** [comment]
Encryption of passwords is currently not supported by the plugin unfortunately. Are you based in Singapore by any chance? It's the only country I know that requires encryption when logging in.

**Comment by Tenelia** [comment]
Yup, I am...

**Comment by Tenelia** [comment]
Would it help if I give you a short encryption code chunk? Am actually learning how to code myself.

**Comment by dan-lind** [comment]
I'm afraid it's not that easy. The plugin uses v3 of the login api, which for some reason does not seem to support encrypted passwords. You can read more here :
https://labs.ig.com/rest-trading-api-reference/service-detail?id=534

**Comment by Tenelia** [comment]
Ah, I see the issues... I'm also trying to look at https://labs.ig.com/loginrestrictions

Could it just be undocumented maybe..?

**Comment by dan-lind** [comment]
I actually tried to implement encryption for the login on the basis that it might just be undocumented for v3 of the API, but could not get it to work. You are free to give it a try of course. Maybe contact IG first and ask if encrypted passwords are supported at all with v3.

**Comment by Tenelia** [comment]
I emailed them and this came back:
******
Thanks for your email.

Our API should support encryption for login.

However, to generate the encrypted password requires 

1) Calling the /session/encryptionKey 

2) Then using timestamp returned from that endpoint to create the string: 

password|timestamp 

3) This needs to encrypted with the public key 

4)The resulting string needs to be encrypted to base64 

5)This final string is the one passed in the password field in the body above. 

Please take a look at https://labs.ig.com/node/295 and https://labs.ig.com/node/420 

Note that the source code for the companion app is available in the browser ... there is an encryption.js which might help. 

If you have any further queries please do not hesitate to contact us. Alternatively, please visit the IG Community where you can share ideas, knowledge and experience with other like-minded traders. 
******
Thoughts?

**Comment by dan-lind** [comment]
Very late answer, I know. But I can't give any more information than I gave already.
The plugin uses v3 of the API. There is no field for encryptedPassword (like there was in v1 and v2).
I have tried putting an encrypted password in both encryptedPassword and the password fields, but the API does not accept the input.
